spring.application.name=gym-system

spring.datasource.url=jdbc:mysql://localhost:3306/gym_system
spring.datasource.username=root
spring.datasource.password=GymRoot2026#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=8080


twilio.account.sid=TU_ACCOUNT_SID
twilio.auth.token=TU_AUTH_TOKEN
twilio.whatsapp.from=+14155238886